name: movie_mind_app
description: A new Flutter project for MovieMind.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.0
  cached_network_image: ^3.3.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  image_picker: ^1.0.7
  video_player: ^2.10.1
  chewie: ^1.13.0
  youtube_player_iframe: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/genres/
    - assets/images/actors/
    - assets/awards/
    - assets/scripts/
